source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '11.0'
inhibit_all_warnings!

target 'VeGamePublicDemo' do
  pod 'Toast'
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'VeGameSDK', '1.36.0'
end
